export SHELL = bash
export CONFIG_HOST := x86_64-cross-linux-gnu
export CONFIG_TARGET := arm-linux-gnueabihf
export CONFIG_HOSTNAME := piclfs
export CONFIG_ROOT_PASSWD := piclfs
export CONFIG_LOCAL_TIMEZONE := Asia/Seoul
export CONFIG_PKG_VERSION := PiCLFS 2017.03
export CONFIG_BUG_URL := https://github.com/LeeKyuHyuk/PiCLFS/issues
export CONFIG_PARALLEL_JOBS := $(shell echo `cat /proc/cpuinfo | grep cores | wc -l `)
export WORKSPACE_DIR := $(shell pwd)
export PACKAGES_DIR := $(WORKSPACE_DIR)/packages
export SCRIPTS_DIR := $(WORKSPACE_DIR)/scripts
export OUTPUT_DIR := $(WORKSPACE_DIR)/out
export BUILD_DIR := $(OUTPUT_DIR)/build
export TOOLS_DIR := $(OUTPUT_DIR)/tools
export KERNEL_DIR := $(OUTPUT_DIR)/kernel
export ROOTFS_DIR := $(OUTPUT_DIR)/rootfs
export IMAGES_DIR := $(OUTPUT_DIR)/images
export SYSROOT_DIR := $(TOOLS_DIR)/usr/$(CONFIG_TARGET)/sysroot
export PATH := "$(TOOLS_DIR)/bin:$(TOOLS_DIR)/sbin:$(TOOLS_DIR)/usr/bin:$(TOOLS_DIR)/usr/sbin:$(PATH)"
export EXTRACT := $(SCRIPTS_DIR)/extract.sh
export STEP := $(SCRIPTS_DIR)/step.sh
export SUCCESS := $(SCRIPTS_DIR)/success.sh
export ERROR := $(SCRIPTS_DIR)/error.sh
